- hosts: all
  tasks: 
    - name: install apache
      yum: name=httpd state=present

    - name: start service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: deploy a website 
      template:
        src: index.j2
        dest: /var/www/html/index.html
        force: yes
    - name: add a rule in firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
      ignore_errors: yes
