- name: using facts
  hosts: node1
  gather_facts: no
  tasks:
    - name: ip address of machine
      debug:
        #msg: "ip address of node1 is {{ ansible_default_ipv4.address }}"
        #msg: 'ip address of node1 is {{ ansible_default_ipv4["address"] }}'
        #msg: '{{ ansible_facts["default_ipv4"]["address"] }}'
        msg: 'ip node1: {{ ansible_facts.default_ipv4.address }}'
