- name: Setup apache webserver
  hosts: all
  become: true
  tasks: 
    - name: install apache server 
      apt:
        name: apache2
        state: present

    - name: Start Service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy a file 
      copy:
        src: website.html
        dest: /var/www/html/index.html
        force: yes
